Fid use of runfiles with spaces (#65)
This change fixes the following error which is caused by a binary using
runfiles with spaces in them
```
 Traceback (most recent call last):
  File "D:\a\rules_venv\rules_venv\python\venv\private\venv_process_wrapper.py", line 329, in <module>
    main()
  File "D:\a\rules_venv\rules_venv\python\venv\private\venv_process_wrapper.py", line 270, in main
    install_files(manifest=Path(runfiles_collection), output_dir=runfiles_dir)
  File "D:\a\rules_venv\rules_venv\python\venv\private\venv_process_wrapper.py", line 209, in install_files
    abs_src = Path(runfiles[dest])
                   ~~~~~~~~^^^^^^
KeyError: '_main/python/venv/private/tests/runfiles_with_spaces/data file.txt'
```